name: "Run playwright tests"

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest


    steps:
      - uses: microsoft/playwright-github-action@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Ensure browsers are installed
        run: python -m playwright install
      - name: Run your tests
        run: pytest search_test.py
